language: node_js
node_js:
- stable
addons:
  apt:
    packages:
    - libgconf-2-4
cache:
  npm: true
  directories:
  - "~/.cache"
  - node_modules
before_install: "./build-env.sh"
install:
- npm install
- npm ci
script:
- npm run cypress:headless
- npm test a
- npm run build
deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: build
  on:
    branch: release
- provider: surge
  skip_cleanup: true
  project: "./build/"
  domain: a-fathers-lullaby.surge.sh
  on:
    branch: master
branches:
  only:
  - master
  - release
env:
  global:
  - secure: DY+LqZPs6q1jqA+NSNzJRYORZJw7NR7tk1474SE3o5jZvUnmpvkkh+lMLLYhi685Xk62Fy8ADFSoIdDwaw4E4xY7i7j5dThHurR9LETuaDQXptMyoab78UEo6wiRPoiIN2ySfgEymgzDho/vHBPNgDzfxQniEkTdrILfSgwu80Cio0xhxOIK6V0hzsgvTS7D7evXklwegvSxcOkCYRwROqtEIEIoX1PZBrNrf6BFb5HWLuU3Nqx6CO+xQgy7E7TwczXKmesWbNKN3lOFR8KCOceJRtb7XTH3M3U04DNy6d7detMXvlT1bC/N27dwnRk05EhD3Ydrb0yeEECtNqxr7Fh8i7pJzZ072enoyD1POlpZOn2JpDZwbBX+GebMNwvHLngIo9Vl1iV20UT/6UU2N4YfN/MOe1e+ZKj2wxN/paJXcSdBlZ7pwQamToR+HJ3LkS/KMPeTxcTNQWPf0wdUFyS47BNTpPvUTQ5v20ZYJt4Z/PAbIu+1QRNPjFjLP3qPzxp1qcreEF+o1Z+yVnJrlT2rMGwkgwIG6xq3AvDsXzBPZ4Fs/6/2uaasxCahzxCZFhjBJ5l7uStyPlZFKWP2LkZda0QOjJzixThTotGreNAm6jj04HTpuF1Ql3UxTjvjILU8/FsJcMklijHX2igv3/m5sTL/TI0choZpNIB+HMw=
